server:
  port: 8080

spring:
  datasource:
    username: root
    password: Ac12345678
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://192.168.31.103:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

indexing-settings:
  sites:
#    - url: https://lenta.ru
#      name: Лента.ру
    - url: https://skillbox.ru
      name: Skillbox
#    - url: https://playback.ru
#      name: PlayBack.Ru

parsing-settings:
  user-agent: SearchBot/2.0
  referer: https://yandex.ru
  timeout: 15_000 # ms
  thread-delay: 150 # ms
  treshhold: 10
  parallelism: 4
